// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: trade.proto

package server

import (
	"context"

	"service_test/rpc/trade/internal/logic"
	"service_test/rpc/trade/internal/svc"
	"service_test/rpc/trade/trade"
)

type TradeServer struct {
	svcCtx *svc.ServiceContext
	trade.UnimplementedTradeServer
}

func NewTradeServer(svcCtx *svc.ServiceContext) *TradeServer {
	return &TradeServer{
		svcCtx: svcCtx,
	}
}

func (s *TradeServer) CreateTrade(ctx context.Context, in *trade.CreateTradeRequest) (*trade.CreateTradeResponse, error) {
	l := logic.NewCreateTradeLogic(ctx, s.svcCtx)
	return l.CreateTrade(in)
}

func (s *TradeServer) GetInstanceInfo(ctx context.Context, in *trade.GetInstanceInfoRequest) (*trade.GetInstanceInfoResponse, error) {
	l := logic.NewGetInstanceInfoLogic(ctx, s.svcCtx)
	return l.GetInstanceInfo(in)
}
