// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: trade.proto

package tradeclient

import (
	"context"

	"service_test/rpc/trade/trade"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateTradeRequest      = trade.CreateTradeRequest
	CreateTradeResponse     = trade.CreateTradeResponse
	GetInstanceInfoRequest  = trade.GetInstanceInfoRequest
	GetInstanceInfoResponse = trade.GetInstanceInfoResponse

	Trade interface {
		CreateTrade(ctx context.Context, in *CreateTradeRequest, opts ...grpc.CallOption) (*CreateTradeResponse, error)
		GetInstanceInfo(ctx context.Context, in *GetInstanceInfoRequest, opts ...grpc.CallOption) (*GetInstanceInfoResponse, error)
	}

	defaultTrade struct {
		cli zrpc.Client
	}
)

func NewTrade(cli zrpc.Client) Trade {
	return &defaultTrade{
		cli: cli,
	}
}

func (m *defaultTrade) CreateTrade(ctx context.Context, in *CreateTradeRequest, opts ...grpc.CallOption) (*CreateTradeResponse, error) {
	client := trade.NewTradeClient(m.cli.Conn())
	return client.CreateTrade(ctx, in, opts...)
}

func (m *defaultTrade) GetInstanceInfo(ctx context.Context, in *GetInstanceInfoRequest, opts ...grpc.CallOption) (*GetInstanceInfoResponse, error) {
	client := trade.NewTradeClient(m.cli.Conn())
	return client.GetInstanceInfo(ctx, in, opts...)
}
