// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: user.proto

package server

import (
	"context"

	"service_test/rpc/user/internal/logic"
	"service_test/rpc/user/internal/svc"
	"service_test/rpc/user/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) GetUserInfo(ctx context.Context, in *user.UserInfoRequest) (*user.UserInfoResponse, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

func (s *UserServer) CallTrade(ctx context.Context, in *user.CallTradeRequest) (*user.CallTradeResponse, error) {
	l := logic.NewCallTradeLogic(ctx, s.svcCtx)
	return l.CallTrade(in)
}
