// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: user.proto

package userclient

import (
	"context"

	"service_test/rpc/user/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CallTradeRequest  = user.CallTradeRequest
	CallTradeResponse = user.CallTradeResponse
	UserInfoRequest   = user.UserInfoRequest
	UserInfoResponse  = user.UserInfoResponse

	User interface {
		GetUserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error)
		CallTrade(ctx context.Context, in *CallTradeRequest, opts ...grpc.CallOption) (*CallTradeResponse, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) GetUserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

func (m *defaultUser) CallTrade(ctx context.Context, in *CallTradeRequest, opts ...grpc.CallOption) (*CallTradeResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.CallTrade(ctx, in, opts...)
}
