// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: product.proto

package productclient

import (
	"context"

	"service_test/rpc/product/product"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ProductInfoRequest  = product.ProductInfoRequest
	ProductInfoResponse = product.ProductInfoResponse
	ReduceStockRequest  = product.ReduceStockRequest
	ReduceStockResponse = product.ReduceStockResponse

	Product interface {
		GetProductInfo(ctx context.Context, in *ProductInfoRequest, opts ...grpc.CallOption) (*ProductInfoResponse, error)
		ReduceStock(ctx context.Context, in *ReduceStockRequest, opts ...grpc.CallOption) (*ReduceStockResponse, error)
	}

	defaultProduct struct {
		cli zrpc.Client
	}
)

func NewProduct(cli zrpc.Client) Product {
	return &defaultProduct{
		cli: cli,
	}
}

func (m *defaultProduct) GetProductInfo(ctx context.Context, in *ProductInfoRequest, opts ...grpc.CallOption) (*ProductInfoResponse, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.GetProductInfo(ctx, in, opts...)
}

func (m *defaultProduct) ReduceStock(ctx context.Context, in *ReduceStockRequest, opts ...grpc.CallOption) (*ReduceStockResponse, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.ReduceStock(ctx, in, opts...)
}
