// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type CreateTradeRequest struct {
	UserId    int64 `json:"user_id"`
	ProductId int64 `json:"product_id"`
	Quantity  int64 `json:"quantity"`
}

type CreateTradeResponse struct {
	TradeId     int64   `json:"trade_id"`
	UserId      int64   `json:"user_id"`
	ProductId   int64   `json:"product_id"`
	Quantity    int64   `json:"quantity"`
	TotalAmount float64 `json:"total_amount"`
	Status      string  `json:"status"`
}

type ProductInfoResponse struct {
	ProductId   int64   `json:"product_id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
	Stock       int64   `json:"stock"`
}

type UserInfoResponse struct {
	UserId    int64  `json:"user_id"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	CreatedAt int64  `json:"created_at"`
}
