// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package handler

import (
	"net/http"

	"service_test/api/web/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/product/:product_id",
				Handler: GetProductInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/trade/create",
				Handler: CreateTradeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/:user_id",
				Handler: GetUserInfoHandler(serverCtx),
			},
		},
	)
}
