// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: product.proto

package server

import (
	"context"

	"service_test/rpc/product/internal/logic"
	"service_test/rpc/product/internal/svc"
	"service_test/rpc/product/product"
)

type ProductServer struct {
	svcCtx *svc.ServiceContext
	product.UnimplementedProductServer
}

func NewProductServer(svcCtx *svc.ServiceContext) *ProductServer {
	return &ProductServer{
		svcCtx: svcCtx,
	}
}

func (s *ProductServer) GetProductInfo(ctx context.Context, in *product.ProductInfoRequest) (*product.ProductInfoResponse, error) {
	l := logic.NewGetProductInfoLogic(ctx, s.svcCtx)
	return l.GetProductInfo(in)
}

func (s *ProductServer) ReduceStock(ctx context.Context, in *product.ReduceStockRequest) (*product.ReduceStockResponse, error) {
	l := logic.NewReduceStockLogic(ctx, s.svcCtx)
	return l.ReduceStock(in)
}
